### ISSUE TITLE
Links Don't Work

### ISSUE THREAD

**Issue by ajsya** [ContourGithub/contourgithub.github.io#1]
Links don't always work on your site.

**Comment by ContourGithub** [comment]
ah, oh yeah! idk why that is :/

**Comment by ajsya** [comment]
I think it's because you don't list the whole link. You just list the end of the link. I think it needs to be like this or it will just add on the page to the end of the browser search bar.

`<!DOCTYPE HTML>
<html>
<head>
<link href="style.css" rel="stylesheet" type="text/css" />
<title>ContourLines</title>
</head>
<body>
<heading>
  <h1>ContourLines</h1>
  <ul>
  <li><a href="index.html">Home</a></li>
  <li><a href="updates.html">Updates</a></li>
  <li class="dropdown">
    <a href="javascript:void(0)" class="dropbtn">Projects</a>
    <div class="dropdown-content">
      <a href="https://contourgithub.github.io/projects/1.html">Simon</a>
      <a href="https://contourgithub.github.io/projects/2.html">How ContourLines Are You?</a>
          <a href="https://contourgithub.github.io/projects/3.hmtl">Parallel1</a>
          <a href="https://contourgithub.github.io/projects/4.html">Charged</a>
        </div>
    </li>
    </ul>
</heading>
</body>
</html>`

**Comment by ajsya** [comment]
I fixed the problem for you. All you need to do is approve the pull request and my edits will save. _Hopefully_

https://github.com/ContourGithub/contourgithub.github.io/pull/2

**Comment by ContourGithub** [comment]
thnx!

**Comment by ajsya** [comment]
Okay, I fixed the other pages for you too. Just approve my pull requests and your good to go.
